language: ruby
rvm: 2.3.0
sudo: false
cache: bundler
services:
  - redis-server
before_script:
  - bundle exec rake db:migrate
script:
  - bundle exec rubocop
  - bundle exec rake spec
  - bundle exec rake brakeman
deploy:
  provider: heroku
  api_key:
    secure: IxY1JxfmJFoMiZCJMfmRx6nr2L8kQOE37nnjh6+4azbxtipKshls9fTMjYJCpJGAraul4nhAHb4AzmnK8SdjCWBjRy84N+is/kMMWqwIk6hKJwQmNhuEn5qj23jVLN3dU7FUqhutTePuzk2wbPHhfHiWWHnAdtZKwLzV9OJ2LFs=
  app:
    master: chinka
  on:
    repo: masarakki/chinka
  run: "rake db:migrate"
