# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84d4cdc2ff57d9b797c0b00aaad8c855d6cedd3fc883fceb1af18ee4887dd05145fa3b6e1035ec7b9bc33845716f5bdd211bfb348722b182441c001f49eb4617

test:
  secret_key_base: 1abc9fe6ba175c82ae06d0077bc699c66f7df9b37a87a7d88bbec8c3ba754b8b1e72ba239c6b3de5adb657a7aa34f64d0d82955a7f84a98ffeafc93387e57bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
